import Database from "better-sqlite3";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { env } from "../config/env.js";

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * schema.sql lives next to this file in src/, and next to the compiled file in dist/
 * (copied by `npm run build`). Fall back to the source tree so `tsx` runs work
 * even before a build has happened.
 */
function readSchema(): string {
  const candidates = [
    resolve(HERE, "schema.sql"),
    resolve(process.cwd(), "src/database/schema.sql"),
    resolve(HERE, "../../src/database/schema.sql"),
  ];
  for (const path of candidates) {
    if (existsSync(path)) return readFileSync(path, "utf8");
  }
  throw new Error(
    `[db] schema.sql not found. Looked in:\n${candidates.map((c) => `  - ${c}`).join("\n")}`,
  );
}

const dbPath = resolve(process.cwd(), env.DATABASE_PATH);
mkdirSync(dirname(dbPath), { recursive: true });

export const db = new Database(dbPath);

// WAL keeps the API server's reads from blocking the agent's writes.
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");
db.pragma("busy_timeout = 5000");

/**
 * Adds a column only if it is missing. SQLite has no `ADD COLUMN IF NOT EXISTS`,
 * so pre-existing databases are upgraded by inspecting PRAGMA table_info.
 */
function addColumnIfMissing(table: string, column: string, definition: string): void {
  const columns = db.prepare(`PRAGMA table_info(${table})`).all() as Array<{ name: string }>;
  if (columns.some((c) => c.name === column)) return;
  db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
  console.log(`[db] migration: added ${table}.${column}`);
}

let initialised = false;

export function initDatabase(): void {
  if (initialised) return;

  db.exec(readSchema());

  // --- Incremental migrations (safe to run on every boot) ---
  addColumnIfMissing("simulated_positions", "confidence_score", "REAL DEFAULT 0");
  addColumnIfMissing("simulated_positions", "last_checked_at", "DATETIME");
  addColumnIfMissing("simulated_positions", "current_price", "REAL");
  addColumnIfMissing("simulated_positions", "impermanent_loss_usd", "REAL DEFAULT 0");
  addColumnIfMissing("simulated_positions", "floating_pnl_usd", "REAL DEFAULT 0");
  addColumnIfMissing("simulated_positions", "entry_sol_price_usd", "REAL");
  addColumnIfMissing("simulated_positions", "close_reason", "TEXT");
  addColumnIfMissing("daily_research_logs", "sentiment_bias", "TEXT");

  // Anti-rug screen results captured at entry.
  addColumnIfMissing("simulated_positions", "top10_holder_pct", "REAL");
  addColumnIfMissing("simulated_positions", "mint_authority_revoked", "INTEGER");
  addColumnIfMissing("simulated_positions", "freeze_authority_revoked", "INTEGER");
  addColumnIfMissing("simulated_positions", "safety_verdict", "TEXT");

  // Dynamic Solana priority-fee estimate captured at entry (round trip: open + close).
  addColumnIfMissing("simulated_positions", "est_gas_cost_usd", "REAL");
  addColumnIfMissing("simulated_positions", "est_priority_micro_lamports", "REAL");

  // Post-trade reflection generated by DeepSeek once the position closes.
  addColumnIfMissing("simulated_positions", "post_mortem", "TEXT");
  addColumnIfMissing("simulated_positions", "post_mortem_at", "DATETIME");

  /*
   * PnL correction. `impermanent_loss_usd` holds divergence-vs-hold, which was
   * previously (and wrongly) treated as the PnL driver. The account-moving figure is
   * position_value_change_usd = notional x (sqrt(r) - 1); realized_pnl_usd is now
   * fees + that. Rows written before this migration used the old, understated
   * definition — the column is added rather than overwritten so that stays visible.
   */
  addColumnIfMissing("simulated_positions", "position_value_change_usd", "REAL DEFAULT 0");
  addColumnIfMissing("simulated_positions", "breakeven_coverage_ratio", "REAL");
  addColumnIfMissing("simulated_positions", "expected_fee_24h_usd", "REAL");

  /*
   * On-chain execution. Every one of these is NULL on a paper row, and that is the
   * point: `execution_mode` is what separates a row describing a real position from a
   * row describing a simulated one, and the two must never be summed as if they were
   * the same kind of fact. A LIVE row without a `position_address` and an
   * `open_signature` describes a position nothing can prove exists.
   *
   * Amounts are recorded as DEPOSITED, in base units, from the confirmed transaction —
   * not from what the engine intended to deposit. The paper columns
   * (`virtual_sol_amount`, `entry_price`) keep their simulated meaning so historical
   * rows stay readable; these sit alongside rather than replacing them.
   */
  addColumnIfMissing("simulated_positions", "execution_mode", "TEXT DEFAULT 'PAPER'");
  addColumnIfMissing("simulated_positions", "position_address", "TEXT");
  addColumnIfMissing("simulated_positions", "open_signature", "TEXT");
  addColumnIfMissing("simulated_positions", "close_signature", "TEXT");
  addColumnIfMissing("simulated_positions", "swap_signature", "TEXT");
  addColumnIfMissing("simulated_positions", "deposited_sol_lamports", "INTEGER");
  addColumnIfMissing("simulated_positions", "deposited_paired_amount", "TEXT");
  /*
   * Wallet reconciliation: the chain-measured lamport balance either side of a LIVE
   * position. Everything else attached to a live row is the paper valuation model,
   * which cannot see swap slippage, priority fees or unrecoverable bin-array rent;
   * these two are the only measurement of what the trade did to the wallet.
   * NULL means "not measured" and must never be read as zero.
   */
  addColumnIfMissing("simulated_positions", "wallet_lamports_before", "INTEGER");
  addColumnIfMissing("simulated_positions", "wallet_lamports_after", "INTEGER");
  addColumnIfMissing("simulated_positions", "rent_paid_lamports", "INTEGER");

  /*
   * Candidates dropped by the execution guard (operator denylist, or the execution
   * breaker). A gate that removes candidates and does not appear in the funnel puts
   * the funnel back in the state it was built to fix: reconstructible only by reading
   * stdout. Zero in paper mode, where the guard does not run.
   */
  addColumnIfMissing("scan_funnel_cycles", "execution_rejected", "INTEGER DEFAULT 0");
  addColumnIfMissing("scan_funnel_cycles", "screener_candidates", "INTEGER");
  addColumnIfMissing("scan_funnel_cycles", "held_excluded", "INTEGER DEFAULT 0");
  addColumnIfMissing("scan_funnel_cycles", "exec_denylist_rejected", "INTEGER DEFAULT 0");
  addColumnIfMissing("scan_funnel_cycles", "exec_breaker_rejected", "INTEGER DEFAULT 0");
  addColumnIfMissing("scan_funnel_cycles", "exec_bincap_rejected", "INTEGER DEFAULT 0");
  addColumnIfMissing("scan_funnel_cycles", "exec_no_wsol_rejected", "INTEGER DEFAULT 0");

  initialised = true;
  console.log(`[db] ready at ${dbPath}`);
}

/** Wraps a function in a transaction. Rolls back if it throws. */
export function transaction<T>(fn: () => T): T {
  return db.transaction(fn)();
}

export function closeDatabase(): void {
  try {
    db.close();
  } catch {
    /* already closed */
  }
}
